version: '3.8'

services:
  app:
    image: ${DOCKER_HUB_USERNAME}/ei-being-app:latest
    ports:
      - "8080:80"
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    command:
      - '-nginx.scrape-uri=http://app/stub_status'

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always